package com.example.demo.user;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Component
@Mapper
//@Repository
public interface UserMapper {
   void newtheme(Integer userid,String title,String data,String text,Integer createtime,Integer replytime,String image,String tags,Integer type,String ycsrc,String fenlei,String themecookie,String lal,String position);
   HashMap gettheme(Integer themeid);
   List getthemelist();
   List getthemelist1();
   List getthemelistby_fenlei(String fenlei,Integer limit);
   List getthemelistby_fenlei1(String fenlei,Integer limit);
   void deletetheme(Integer themeid);
   HashMap login(String email,String password);
   void setcookie(String cookie,Integer userid);
   void set_app_cookie(String cookie,Integer userid);
   String getuserheadimage(Integer userid);
   String getusername(Integer username);
   HashMap getusername1(Integer username);
   HashMap getuserbyemail(String email);
   List getmypattention1(HashMap map);
   void register(String email,String password,String emailtest,Integer registertime);
   void reregister(String email,String password,String emailtest,Integer registertime);
   HashMap findemailtest(String emailtest);
   HashMap getuserbyusername(String username);
   void setusernameby_emailtest(String emailtest,String username);
   void setuserbackgroundimage(Integer userid,String userbackgroundimage);
   void setuserheadimage(Integer userid,String userheadimage);
   Integer jugeadmin(String cookie);
   void settop(Integer themeid);
   void setjing(Integer themeid);
   void deletetop(Integer themeid);
   void deletejing(Integer themeid);
   List getthemelist_jing();
   List getthemelist_top();
   void lookadd(Integer themeid);
   HashMap getuserbycookie(String cookie);
   List getfenlei();
   List getfenleilist();
   List getmylike(Integer userid);
   void setmylike(Integer userid,Integer themeid);
   void deletemylike(Integer userid,Integer themeid);
   void likeadd(Integer themeid);
   void likecut(Integer themeid);
   HashMap getmyself(String cookie);
   HashMap getheself(Integer userid);
   List getthemelistby_user(Integer userid,Integer limit);
   void setsign(String cookie,String sign);
   void setusertoutu(Integer userid,String toutu);
   String getsign(Integer userid);
   Integer getlouceng(Integer themeid);
   void loucengadd(Integer themeid);
   void numadd(Integer themeid);
   void newreply(Integer themeid,Integer userid,String data,String image,Integer louceng,String time);
   void newreply_in(Integer themeid,Integer userid,String data,Integer louceng,String time);
   List getreply(HashMap map);
   List getreply_author(HashMap map);
   List getreply1(HashMap map);
   String getcookie(Integer userid);
   Integer getadmin(String cookie);
   Integer getuseridbylouceng(Integer themeid,Integer louceng);
   void deletelouceng(Integer themeid,Integer louceng);
   Integer getadminbyuserid(Integer userid);
   List getmysave(Integer userid);
   void saveadd(Integer userid,Integer themeid);
   void savedelete(Integer userid,Integer themeid);
   void setthemereplytime(Integer themeid,Integer time);
   List getmyattention(Integer userid);
   void addattention(Integer a,Integer b);
   void deleteattention(Integer a,Integer b);
   List getmyattentionlist(HashMap map);
   List getmyfanslist(HashMap map );
   void addattentionnum(Integer a);
   void addfansnum(Integer b);
   void deleteattentionnum(Integer a);
   void deletefansnum(Integer b);
   void userlikecut(Integer themeid);
   void userlikeadd(Integer themeid);
   void updatehot(Integer time);
   List getthemelistby_hot();
   void user_visit(Integer userid,Integer time);
   void userhot(Integer time);
   List userhotlist();
   List getmysavelist( HashMap map);
   List getmylikelist( HashMap map);
   void addtag(String themecookie,String tag);
   List hottag();
   List getthemelistby_tag(HashMap map);
   List getthemelistby_tag1(String tag);
   List getthemelistby_fenlei2(String fenlei,Integer userid,Integer limit);
   List getthemelistby_fenlei0(Integer limit);
   List getthemelistby_fenlei11(Integer limit);
   List getthemelistby_fenlei22(Integer userid,Integer limit);
   List searchuser(String key);
   List searchtheme(String key,Integer limit);
   List getusermessage(String userid,String username,String email);
   void themenumadd(Integer userid);
   void themenumcut(Integer themeid);
   void changepassword(HashMap map);
   void changepassword1(HashMap map);
   void changemessage(HashMap map);
   void setfindpassword(HashMap map);
   void ban(HashMap map);
   List getfenleis();
   void newfenlei(HashMap map);
   void deletefenlei(HashMap map);
   List searchtheme_admin(HashMap map);
   Integer searchtheme_admin_num(HashMap map);
   void deletetheme_admin(HashMap map);
   void huifutheme_admin(HashMap map);
   void deletetop_admin(HashMap map);
   void settop_admin(HashMap map);
   void deletejing_admin(HashMap map);
   void setjing_admin(HashMap map);
   List getmessage();
   List getreply_admin(HashMap map);
   void setbirthday(HashMap map);
   Integer getreply_admin_num(HashMap map);
   void deletereply_admin(HashMap map);
   void huifureply_admin(HashMap map);
   Integer gettodayregister(Integer time);
   Integer gettodayhotuser(String time);
   Integer gettodaynewtheme(Integer time);
   Integer gettodaynewreply(Integer time);
   Integer gettotleusernum();
   Integer gettotlethemenum();
   Integer gettotlereplynum();
   Integer getjingnum();
   void user_visit1(Integer userid,String time,Integer times);
   Integer juge_user_visit(Integer userid,String time);
   void resetlogintime(Integer times);
   List getfenleichart();
   List gethotagschart();
   List getall_systemmessage();
   Integer jugeuserban(HashMap map);
   List getreplymessage(HashMap map);
   List getreplymessage1(HashMap map);
   Integer getreplymessagenum(HashMap map);
   List searchpassword(HashMap map);
   List finduserby_findpassword(HashMap map);
   void changepassword_byemail(HashMap map);
   void deletesystemmessage(HashMap map);
   void replysystemmessage(HashMap map);
   void newsystemmessage(HashMap map);
   List getmy_systemmessage(HashMap map);
   void newchat(Map map);
   void setfenleimoren(HashMap map);
   HashMap getmychat(Integer a,Integer b);
   List getmychatlist(HashMap map);
   HashMap getchatinfo(Integer userid);
   List getidentity(Integer id);
   List getinterest(Integer id);
   List getfenleilistid();
   void newidentity(HashMap map);
   void deleteidentity(HashMap map);
   void newinterest(HashMap map);
   void deleteinterest(HashMap map);
   List getidentitylist();
   List getinterestlist();
   void deletemyshenfen(Integer userid);
   void setmyshenfen(HashMap map);
   List getmyshenfen(HashMap map);
   HashMap getmyshenfen1(Integer id,Integer userid);
   HashMap getmyshenfen2(Integer id,Integer userid);
   List tuijianuser(Integer userid);
   List tuijianuser1(List list);
   List tuijianuser2(List list);
   List getmyshenfenid(HashMap map);
   List getmypattention(HashMap map);
   List getattentionidlist(HashMap map);
   Integer gettuijian_cd(HashMap map);
   void settuijian_cd(Integer userid,Integer time);
   HashMap getlastpattention(HashMap map);
   void setlastpattention(Integer userid1,Integer userid2);
   void jugebanout(Integer userid,Integer now);
   void backmessage(Integer id);
   HashMap getmessage1(Integer id);
   HashMap getmessage2(String cookie);
   List getloucengreply(Integer themeid,Integer louceng);
   void newloucengreply(HashMap map);
   Integer getreplylouceng_id(String cookie);
   void deleteloucengreply(HashMap map);
   List getreplylouceng_admin(HashMap map);
   Integer getreplylouceng_admin_num(HashMap map);
   void huifuloucengreply_admin(HashMap map);
   void deletloucengereply_admin(HashMap map);
   void deletetags(String themecookie);
   void changetheme(HashMap map);
   String getpixivdate();
   void newpixiv(Map map);
   List getpixiv_pc(HashMap map);
   List getpixiv_pe(HashMap map);
   List getpixiv(String date);
   void newpixivtheme(HashMap map);
   Integer getpixivcount(String str);
   HashMap getuseridbyemail(HashMap map);
   List test1();
   HashMap getthemeby_themecookie(String themecookie);
   Integer getthemelistnum(Integer userid);
   List hotthemelist();
   HashMap getuserinfo(Integer userid);
   HashMap getheadborder(Integer userid);
   HashMap getpianyi(String url);
   List getheadborderlist();
   void newheadborder(HashMap map);
   void updateheadborder(HashMap map);
   List getuserheadborder1(Integer userid);
   List getuserheadborder2(Integer userid);
   void deleteuserheadborder(HashMap map);
   void adduserheadborder(HashMap map);
   Integer getheadborderid(Integer userid);
   void setuserheadborder(HashMap map);
   List getactivity(HashMap map);
   List getactivity1(HashMap map);
   Integer jugeactivity(Integer themeid);
   void setactivity(HashMap map);
   void deleteactivity(HashMap map);
   List getskinlist();

   Integer gethottagnum(HashMap map);
   List gettable1();
   List gettable2();
   List getmusiclist();
   List getupdatenotes();
}
